### ISSUE TITLE
Site wont run with the default setup

### ISSUE THREAD

**Issue by jemayn** [umbraco/UI-Examples#8]
Hey there!

Wanted to contribute something to this repo so started by cloning it down. With the connection string and version number both being filled out in the .website web.config the site will not start up:

![image](https://user-images.githubusercontent.com/79840720/111918412-3df9da00-8a85-11eb-8039-3e34915b59c1.png)

If you remove the version in [web.config](https://github.com/umbraco/UI-Examples/blob/master/src/UIExamples.Website/Web.config#L32) the installer will run for fresh clones and set up the db, etc as normally 🙂

**Comment by Rockerby** [comment]
Evening Jesper!

Hope everything's going well. Thanks for flagging - this looks like a nice easy one to fix up.

**Comment by Matthew-Wise** [comment]
One way to solve this would be to upgrade to a version that supports unattended installs, if this an acceptable option Ill do it :)

**Comment by ronaldbarendse** [comment]
PR https://github.com/umbraco/UI-Examples/pull/27 updates the sample site to use unattended install, so you will now get an up-and-running site right after startup👍🏻
